#!/usr/bin/env bash

# ── AgToosa: file lists and usage text ───────────────────────
# Sourced by agtoosa.sh. Globals: AGTOOSA_VERSION (read-only here).

DOCS_FILES=(
  "Docs/AgToosa_Agent.md"
  "Docs/AgToosa_Quickref.md"
  "Docs/agtoosa-verify.sh"
  "Docs/agtoosa-gate.yml.example"
  "Docs/AgToosa_Init.md"
  "Docs/AgToosa_Spec.md"
  "Docs/AgToosa_Build.md"
  "Docs/AgToosa_Review.md"
  "Docs/AgToosa_CrossModelReview.md"
  "Docs/AgToosa_AgentCapability.md"
  "Docs/AgToosa_Ship.md"
  "Docs/AgToosa_QA.md"
  "Docs/AgToosa_Revert.md"
  "Docs/AgToosa_Task.md"
  "Docs/AgToosa_Handoff.md"
  "Docs/AgToosa_Import.md"
  "Docs/AgToosa_Evidence.md"
  "Docs/agtoosa-evidence.jsonl"
  "Docs/AgToosa_MetricsKit.md"
  "Docs/AgToosa_CaseStudy.template.md"
  "Docs/AgToosa_Status.md"
  "Docs/AgToosa_StatusGuide.md"
  "Docs/AgToosa_Readiness.md"
  "Docs/AgToosa_Goal.md"
  "Docs/AgToosa_Debug.md"
  "Docs/AgToosa_Concise.md"
  "Docs/AgToosa_Update.md"
  "Docs/AgToosa_Registry.md"
  "Docs/AgToosa_Catalog.md"
  "Docs/AgToosa_Skills.md"
  "Docs/AgToosa_Specialists.md"
  "Docs/CONTEXT-FORMAT.md"
  "Docs/ADR-FORMAT.md"
  "Docs/SPEC-FORMAT.md"
  "Docs/DEEPENING.md"
  "Docs/LANGUAGE.md"
  "Docs/AgToosa_Governance.md"
  "Docs/Master-Architecture.md"
  "Docs/Master-Plan.md"
  "Docs/AgToosa_Changelog.md"
)

OPTIONAL_TEMPLATE_FILES=(
  "Docs/AgToosa_Claude.md"
  "Docs/AgToosa_Gemini.md"
  ".cursorrules"
  ".windsurfrules"
  "CLAUDE.md"
  "AGENTS.md"
  ".github/copilot-instructions.md"
  "OPENCODE.md"
  ".claude/commands/agtoosa-init.md"
  ".claude/commands/agtoosa-spec.md"
  ".claude/commands/agtoosa-build.md"
  ".claude/commands/agtoosa-qa.md"
  ".claude/commands/agtoosa-review.md"
  ".claude/commands/agtoosa-ship.md"
  ".claude/commands/agtoosa-revert.md"
  ".claude/commands/agtoosa-task.md"
  ".claude/commands/agtoosa-handoff.md"
  ".claude/commands/agtoosa-import.md"
  ".claude/commands/agtoosa-evidence.md"
  ".claude/commands/agtoosa-update.md"
  ".claude/commands/agtoosa-status.md"
  ".claude/commands/agtoosa-goal.md"
  ".claude/commands/agtoosa-help.md"
  ".claude/settings.json"
  ".claude/hooks/block-dangerous-git.sh"
  ".claude/commands/agtoosa-debug.md"
  ".claude/commands/agtoosa-concise.md"
  ".claude/commands/agtoosa-catalog.md"
  ".cursor/commands/agtoosa-init.md"
  ".cursor/commands/agtoosa-spec.md"
  ".cursor/commands/agtoosa-build.md"
  ".cursor/commands/agtoosa-qa.md"
  ".cursor/commands/agtoosa-review.md"
  ".cursor/commands/agtoosa-ship.md"
  ".cursor/commands/agtoosa-revert.md"
  ".cursor/commands/agtoosa-task.md"
  ".cursor/commands/agtoosa-handoff.md"
  ".cursor/commands/agtoosa-import.md"
  ".cursor/commands/agtoosa-evidence.md"
  ".cursor/commands/agtoosa-update.md"
  ".cursor/commands/agtoosa-status.md"
  ".cursor/commands/agtoosa-goal.md"
  ".cursor/commands/agtoosa-help.md"
  ".cursor/commands/agtoosa-debug.md"
  ".cursor/commands/agtoosa-concise.md"
  ".cursor/commands/agtoosa-catalog.md"
  ".cursor/rules/agtoosa-concise.mdc"
  ".windsurf/rules/agtoosa-debug.md"
  ".windsurf/rules/agtoosa-concise.md"
  ".gemini/commands/agtoosa-debug.toml"
  ".gemini/commands/agtoosa-concise.toml"
  ".gemini/commands/agtoosa-catalog.toml"
  ".github/prompts/agtoosa-concise.prompt.md"
  ".github/prompts/agtoosa-catalog.prompt.md"
  ".cursor/rules/agtoosa-core.mdc"
  ".cursor/rules/agtoosa-spec.mdc"
  ".cursor/rules/agtoosa-build.mdc"
  ".cursor/rules/agtoosa-qa.mdc"
  ".cursor/rules/agtoosa-review.mdc"
  ".cursor/rules/agtoosa-ship.mdc"
  ".cursor/rules/agtoosa-revert.mdc"
  ".cursor/rules/agtoosa-task.mdc"
  ".cursor/rules/agtoosa-handoff.mdc"
  ".cursor/rules/agtoosa-import.mdc"
  ".cursor/rules/agtoosa-evidence.mdc"
  ".cursor/rules/agtoosa-update.mdc"
  ".cursor/rules/agtoosa-status.mdc"
  ".cursor/rules/agtoosa-goal.mdc"
  ".gemini/commands/agtoosa-init.toml"
  ".gemini/commands/agtoosa-spec.toml"
  ".gemini/commands/agtoosa-build.toml"
  ".gemini/commands/agtoosa-qa.toml"
  ".gemini/commands/agtoosa-review.toml"
  ".gemini/commands/agtoosa-ship.toml"
  ".gemini/commands/agtoosa-revert.toml"
  ".gemini/commands/agtoosa-task.toml"
  ".gemini/commands/agtoosa-handoff.toml"
  ".gemini/commands/agtoosa-import.toml"
  ".gemini/commands/agtoosa-evidence.toml"
  ".gemini/commands/agtoosa-update.toml"
  ".gemini/commands/agtoosa-status.toml"
  ".gemini/commands/agtoosa-goal.toml"
  ".gemini/commands/agtoosa-help.toml"
  ".github/prompts/agtoosa-init.prompt.md"
  ".github/prompts/agtoosa-spec.prompt.md"
  ".github/prompts/agtoosa-build.prompt.md"
  ".github/prompts/agtoosa-qa.prompt.md"
  ".github/prompts/agtoosa-review.prompt.md"
  ".github/prompts/agtoosa-ship.prompt.md"
  ".github/prompts/agtoosa-revert.prompt.md"
  ".github/prompts/agtoosa-task.prompt.md"
  ".github/prompts/agtoosa-handoff.prompt.md"
  ".github/prompts/agtoosa-import.prompt.md"
  ".github/prompts/agtoosa-evidence.prompt.md"
  ".github/prompts/agtoosa-update.prompt.md"
  ".github/prompts/agtoosa-status.prompt.md"
  ".github/prompts/agtoosa-goal.prompt.md"
  ".github/prompts/agtoosa-help.prompt.md"
  ".github/agents/agtoosa.agent.md"
  ".github/agents/agtoosa-status-guide.agent.md"
  ".github/agents/agtoosa-cross-model-reviewer.agent.md"
  ".github/instructions/agtoosa-core.instructions.md"
  ".github/instructions/agtoosa-testing.instructions.md"
  ".github/instructions/agtoosa-security.instructions.md"
  ".github/instructions/agtoosa-changelog.instructions.md"
  ".codex/skills/agtoosa-init/SKILL.md"
  ".codex/skills/agtoosa-spec/SKILL.md"
  ".codex/skills/agtoosa-build/SKILL.md"
  ".codex/skills/agtoosa-qa/SKILL.md"
  ".codex/skills/agtoosa-review/SKILL.md"
  ".codex/skills/agtoosa-ship/SKILL.md"
  ".codex/skills/agtoosa-revert/SKILL.md"
  ".codex/skills/agtoosa-task/SKILL.md"
  ".codex/skills/agtoosa-handoff/SKILL.md"
  ".codex/skills/agtoosa-import/SKILL.md"
  ".codex/skills/agtoosa-evidence/SKILL.md"
  ".codex/skills/agtoosa-update/SKILL.md"
  ".codex/skills/agtoosa-status/SKILL.md"
  ".codex/skills/agtoosa-goal/SKILL.md"
  ".codex/skills/agtoosa-help/SKILL.md"
  ".codex/skills/agtoosa-debug/SKILL.md"
  ".codex/skills/agtoosa-concise/SKILL.md"
  ".codex/prompts/agtoosa-init.md"
  ".codex/prompts/agtoosa-spec.md"
  ".codex/prompts/agtoosa-build.md"
  ".codex/prompts/agtoosa-qa.md"
  ".codex/prompts/agtoosa-review.md"
  ".codex/prompts/agtoosa-ship.md"
  ".codex/prompts/agtoosa-revert.md"
  ".codex/prompts/agtoosa-task.md"
  ".codex/prompts/agtoosa-handoff.md"
  ".codex/prompts/agtoosa-import.md"
  ".codex/prompts/agtoosa-evidence.md"
  ".codex/prompts/agtoosa-update.md"
  ".codex/prompts/agtoosa-status.md"
  ".codex/prompts/agtoosa-goal.md"
  ".codex/prompts/agtoosa-help.md"
  ".codex/prompts/agtoosa-debug.md"
  ".codex/prompts/agtoosa-concise.md"
  ".codex/prompts/agtoosa-catalog.md"
  ".windsurf/rules/agtoosa-spec.md"
  ".windsurf/rules/agtoosa-build.md"
  ".windsurf/rules/agtoosa-qa.md"
  ".windsurf/rules/agtoosa-review.md"
  ".windsurf/rules/agtoosa-ship.md"
  ".windsurf/rules/agtoosa-revert.md"
  ".windsurf/rules/agtoosa-task.md"
  ".windsurf/rules/agtoosa-handoff.md"
  ".windsurf/rules/agtoosa-import.md"
  ".windsurf/rules/agtoosa-evidence.md"
  ".windsurf/rules/agtoosa-update.md"
  ".windsurf/rules/agtoosa-status.md"
  ".windsurf/rules/agtoosa-goal.md"
  ".windsurf/workflows/agtoosa-init.md"
  ".windsurf/workflows/agtoosa-spec.md"
  ".windsurf/workflows/agtoosa-build.md"
  ".windsurf/workflows/agtoosa-qa.md"
  ".windsurf/workflows/agtoosa-review.md"
  ".windsurf/workflows/agtoosa-ship.md"
  ".windsurf/workflows/agtoosa-revert.md"
  ".windsurf/workflows/agtoosa-task.md"
  ".windsurf/workflows/agtoosa-handoff.md"
  ".windsurf/workflows/agtoosa-import.md"
  ".windsurf/workflows/agtoosa-evidence.md"
  ".windsurf/workflows/agtoosa-update.md"
  ".windsurf/workflows/agtoosa-status.md"
  ".windsurf/workflows/agtoosa-goal.md"
  ".windsurf/workflows/agtoosa-help.md"
  ".windsurf/workflows/agtoosa-debug.md"
  ".windsurf/workflows/agtoosa-concise.md"
  ".windsurf/workflows/agtoosa-catalog.md"
)

CONTEXT_FILES=(
  "Docs/Context/workflow.md"
  "Docs/Context/tech-stack.md"
  "Docs/Context/product.md"
  "Docs/Context/product-guidelines.md"
)

CLAUDE_COMMAND_FILES=(
  ".claude/commands/agtoosa-init.md"
  ".claude/commands/agtoosa-spec.md"
  ".claude/commands/agtoosa-build.md"
  ".claude/commands/agtoosa-qa.md"
  ".claude/commands/agtoosa-review.md"
  ".claude/commands/agtoosa-ship.md"
  ".claude/commands/agtoosa-revert.md"
  ".claude/commands/agtoosa-task.md"
  ".claude/commands/agtoosa-handoff.md"
  ".claude/commands/agtoosa-import.md"
  ".claude/commands/agtoosa-evidence.md"
  ".claude/commands/agtoosa-update.md"
  ".claude/commands/agtoosa-status.md"
  ".claude/commands/agtoosa-goal.md"
  ".claude/commands/agtoosa-help.md"
  ".claude/commands/agtoosa-debug.md"
  ".claude/commands/agtoosa-concise.md"
  ".claude/commands/agtoosa-catalog.md"
)

CLAUDE_SKILL_FILES=(
  ".claude/skills/agtoosa-review.md"
  ".claude/skills/agtoosa-debug.md"
)

CLAUDE_HOOK_FILES=(
  ".claude/hooks/block-dangerous-git.sh"
)

CURSOR_RULE_FILES=(
  ".cursor/rules/agtoosa-core.mdc"
  ".cursor/rules/agtoosa-spec.mdc"
  ".cursor/rules/agtoosa-build.mdc"
  ".cursor/rules/agtoosa-qa.mdc"
  ".cursor/rules/agtoosa-review.mdc"
  ".cursor/rules/agtoosa-ship.mdc"
  ".cursor/rules/agtoosa-revert.mdc"
  ".cursor/rules/agtoosa-task.mdc"
  ".cursor/rules/agtoosa-handoff.mdc"
  ".cursor/rules/agtoosa-import.mdc"
  ".cursor/rules/agtoosa-evidence.mdc"
  ".cursor/rules/agtoosa-update.mdc"
  ".cursor/rules/agtoosa-status.mdc"
  ".cursor/rules/agtoosa-goal.mdc"
  ".cursor/rules/agtoosa-debug.mdc"
  ".cursor/rules/agtoosa-concise.mdc"
)

CURSOR_COMMAND_FILES=(
  ".cursor/commands/agtoosa-init.md"
  ".cursor/commands/agtoosa-spec.md"
  ".cursor/commands/agtoosa-build.md"
  ".cursor/commands/agtoosa-qa.md"
  ".cursor/commands/agtoosa-review.md"
  ".cursor/commands/agtoosa-ship.md"
  ".cursor/commands/agtoosa-revert.md"
  ".cursor/commands/agtoosa-task.md"
  ".cursor/commands/agtoosa-handoff.md"
  ".cursor/commands/agtoosa-import.md"
  ".cursor/commands/agtoosa-evidence.md"
  ".cursor/commands/agtoosa-update.md"
  ".cursor/commands/agtoosa-status.md"
  ".cursor/commands/agtoosa-goal.md"
  ".cursor/commands/agtoosa-help.md"
  ".cursor/commands/agtoosa-debug.md"
  ".cursor/commands/agtoosa-concise.md"
  ".cursor/commands/agtoosa-catalog.md"
)

GEMINI_COMMAND_FILES=(
  ".gemini/commands/agtoosa-init.toml"
  ".gemini/commands/agtoosa-spec.toml"
  ".gemini/commands/agtoosa-build.toml"
  ".gemini/commands/agtoosa-qa.toml"
  ".gemini/commands/agtoosa-review.toml"
  ".gemini/commands/agtoosa-ship.toml"
  ".gemini/commands/agtoosa-revert.toml"
  ".gemini/commands/agtoosa-task.toml"
  ".gemini/commands/agtoosa-handoff.toml"
  ".gemini/commands/agtoosa-import.toml"
  ".gemini/commands/agtoosa-evidence.toml"
  ".gemini/commands/agtoosa-update.toml"
  ".gemini/commands/agtoosa-status.toml"
  ".gemini/commands/agtoosa-goal.toml"
  ".gemini/commands/agtoosa-help.toml"
  ".gemini/commands/agtoosa-debug.toml"
  ".gemini/commands/agtoosa-concise.toml"
  ".gemini/commands/agtoosa-catalog.toml"
)

COPILOT_PROMPT_FILES=(
  ".github/prompts/agtoosa-init.prompt.md"
  ".github/prompts/agtoosa-spec.prompt.md"
  ".github/prompts/agtoosa-build.prompt.md"
  ".github/prompts/agtoosa-qa.prompt.md"
  ".github/prompts/agtoosa-review.prompt.md"
  ".github/prompts/agtoosa-ship.prompt.md"
  ".github/prompts/agtoosa-revert.prompt.md"
  ".github/prompts/agtoosa-task.prompt.md"
  ".github/prompts/agtoosa-handoff.prompt.md"
  ".github/prompts/agtoosa-import.prompt.md"
  ".github/prompts/agtoosa-evidence.prompt.md"
  ".github/prompts/agtoosa-update.prompt.md"
  ".github/prompts/agtoosa-status.prompt.md"
  ".github/prompts/agtoosa-goal.prompt.md"
  ".github/prompts/agtoosa-help.prompt.md"
  ".github/prompts/agtoosa-debug.prompt.md"
  ".github/prompts/agtoosa-concise.prompt.md"
  ".github/prompts/agtoosa-catalog.prompt.md"
)

COPILOT_AGENT_FILES=(
  ".github/agents/agtoosa.agent.md"
  ".github/agents/agtoosa-status-guide.agent.md"
  ".github/agents/agtoosa-cross-model-reviewer.agent.md"
)

COPILOT_INSTRUCTION_FILES=(
  ".github/instructions/agtoosa-core.instructions.md"
  ".github/instructions/agtoosa-testing.instructions.md"
  ".github/instructions/agtoosa-security.instructions.md"
  ".github/instructions/agtoosa-changelog.instructions.md"
)

WINDSURF_RULE_FILES=(
  ".windsurf/rules/agtoosa-core.md"
  ".windsurf/rules/agtoosa-spec.md"
  ".windsurf/rules/agtoosa-build.md"
  ".windsurf/rules/agtoosa-qa.md"
  ".windsurf/rules/agtoosa-review.md"
  ".windsurf/rules/agtoosa-ship.md"
  ".windsurf/rules/agtoosa-revert.md"
  ".windsurf/rules/agtoosa-task.md"
  ".windsurf/rules/agtoosa-handoff.md"
  ".windsurf/rules/agtoosa-import.md"
  ".windsurf/rules/agtoosa-evidence.md"
  ".windsurf/rules/agtoosa-update.md"
  ".windsurf/rules/agtoosa-status.md"
  ".windsurf/rules/agtoosa-goal.md"
  ".windsurf/rules/agtoosa-debug.md"
  ".windsurf/rules/agtoosa-concise.md"
)

WINDSURF_WORKFLOW_FILES=(
  ".windsurf/workflows/agtoosa-init.md"
  ".windsurf/workflows/agtoosa-spec.md"
  ".windsurf/workflows/agtoosa-build.md"
  ".windsurf/workflows/agtoosa-qa.md"
  ".windsurf/workflows/agtoosa-review.md"
  ".windsurf/workflows/agtoosa-ship.md"
  ".windsurf/workflows/agtoosa-revert.md"
  ".windsurf/workflows/agtoosa-task.md"
  ".windsurf/workflows/agtoosa-handoff.md"
  ".windsurf/workflows/agtoosa-import.md"
  ".windsurf/workflows/agtoosa-evidence.md"
  ".windsurf/workflows/agtoosa-update.md"
  ".windsurf/workflows/agtoosa-status.md"
  ".windsurf/workflows/agtoosa-goal.md"
  ".windsurf/workflows/agtoosa-help.md"
  ".windsurf/workflows/agtoosa-debug.md"
  ".windsurf/workflows/agtoosa-concise.md"
  ".windsurf/workflows/agtoosa-catalog.md"
)

CODEX_SKILL_FILES=(
  ".codex/skills/agtoosa-init/SKILL.md"
  ".codex/skills/agtoosa-spec/SKILL.md"
  ".codex/skills/agtoosa-build/SKILL.md"
  ".codex/skills/agtoosa-qa/SKILL.md"
  ".codex/skills/agtoosa-review/SKILL.md"
  ".codex/skills/agtoosa-ship/SKILL.md"
  ".codex/skills/agtoosa-revert/SKILL.md"
  ".codex/skills/agtoosa-task/SKILL.md"
  ".codex/skills/agtoosa-handoff/SKILL.md"
  ".codex/skills/agtoosa-import/SKILL.md"
  ".codex/skills/agtoosa-evidence/SKILL.md"
  ".codex/skills/agtoosa-update/SKILL.md"
  ".codex/skills/agtoosa-status/SKILL.md"
  ".codex/skills/agtoosa-goal/SKILL.md"
  ".codex/skills/agtoosa-help/SKILL.md"
  ".codex/skills/agtoosa-debug/SKILL.md"
  ".codex/skills/agtoosa-concise/SKILL.md"
)

CODEX_PROMPT_FILES=(
  ".codex/prompts/agtoosa-init.md"
  ".codex/prompts/agtoosa-spec.md"
  ".codex/prompts/agtoosa-build.md"
  ".codex/prompts/agtoosa-qa.md"
  ".codex/prompts/agtoosa-review.md"
  ".codex/prompts/agtoosa-ship.md"
  ".codex/prompts/agtoosa-revert.md"
  ".codex/prompts/agtoosa-task.md"
  ".codex/prompts/agtoosa-handoff.md"
  ".codex/prompts/agtoosa-import.md"
  ".codex/prompts/agtoosa-evidence.md"
  ".codex/prompts/agtoosa-update.md"
  ".codex/prompts/agtoosa-status.md"
  ".codex/prompts/agtoosa-goal.md"
  ".codex/prompts/agtoosa-help.md"
  ".codex/prompts/agtoosa-debug.md"
  ".codex/prompts/agtoosa-concise.md"
  ".codex/prompts/agtoosa-catalog.md"
)

print_usage() {
  echo "AgToosa Generator v${AGTOOSA_VERSION}"
  echo ""
  echo "Usage: bash agtoosa.sh [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  --registry <cmd> [arg] Manage template packs from the community registry"
  echo "                           list              — List available packs"
  echo "                           search <keyword>  — Search packs by keyword"
  echo "                           info <name>       — Show pack details"
  echo "                           install <name>    — Download and install a pack"
  echo "                           publish           — Contribution wizard for pack authors"
  echo "  --catalog <cmd> [arg]  Discover extensions/presets (read-only; installs use --registry)"
  echo "                           list              — List catalog entries"
  echo "                           search <keyword>  — Search by tag, name, or summary"
  echo "                           info <id>         — Show entry details and compatibility"
  echo "                           validate <path>   — Validate a catalog JSON file"
  echo "                           plan <preset-id>  — Emit non-executing registry install plan"
  echo "  --update [path]        Update an existing AgToosa install (skips interactive wizard)"
  echo "  --verify [path]        Run the deterministic AgToosa lifecycle verifier (read-only)"
  echo "  --doctor [path]        Diagnose an AgToosa install (versions, wiring, context health)"
  echo "  --uninstall [path]     Remove AgToosa-owned files from a project (keeps your data)"
  echo "  --path <dir>           Project path (skips the interactive path prompt)"
  echo "  --platforms <list>     Comma-separated platforms, e.g. cursor,claude (skips prompt)"
  echo "  --yes, -y              Assume yes for confirmation prompts (non-interactive)"
  echo "  --allow-unverified     Permit --registry install of packs not marked verified"
  echo "  AGTOOSA_MINISIGN_PUBKEY  Override path to minisign public key (optional soft-warn verify)"
  echo "  --force                Overwrite existing platform config files (creates .bak backups)"
  echo "  --dry-run              Show what would be copied without making changes"
  echo "  --list-template-files  Print every template file path and exit"
  echo "  --version              Print version and exit"
  echo "  --help                 Show this help message"
}

print_template_files() {
  printf '%s\n' "${DOCS_FILES[@]}" "${OPTIONAL_TEMPLATE_FILES[@]}" "${CONTEXT_FILES[@]}"
}
